from django.core.management.base import BaseCommand
from habits.models import Language, Habit, Step  # Make sure to import Step

class Command(BaseCommand):
    help = 'Populate the database with initial data for languages, habits, and steps'

    def handle(self, *args, **kwargs):
        # Adding languages
        languages_data = [
            {'language_code': 'en', 'language_name': 'English'},
            {'language_code': 'ro', 'language_name': 'Romanian'},
            {'language_code': 'ru', 'language_name': 'Russian'}
        ]
        for lang in languages_data:
            Language.objects.get_or_create(language_code=lang['language_code'], defaults={'language_name': lang['language_name']})

        self.stdout.write(self.style.SUCCESS('Successfully added languages'))

        # Adding habits
        habits_data = [
            {'language_code': 'en', 'habit_name': 'Smoking', 'habit_type': 'bad', 'description': 'We help you quit smoking'},
            {'language_code': 'en', 'habit_name': 'Underslept', 'habit_type': 'bad', 'description': 'We help you get more sleep'},
            {'language_code': 'en', 'habit_name': 'Alcohol', 'habit_type': 'bad', 'description': 'We help you get rid of your alcohol addiction'},
            {'language_code': 'en', 'habit_name': 'Overeating', 'habit_type': 'bad', 'description': 'We help you control your appetite'},
            {'language_code': 'en', 'habit_name': 'Procrastination', 'habit_type': 'bad', 'description': 'We help you get over procrastination'},
            {'language_code': 'en', 'habit_name': 'Reading', 'habit_type': 'good', 'description': 'We help you get into reading'},
            {'language_code': 'en', 'habit_name': 'Savings', 'habit_type': 'good', 'description': 'We help you start saving more money'},
            {'language_code': 'en', 'habit_name': 'Gym', 'habit_type': 'good', 'description': 'We help you get into shape'},
            {'language_code': 'en', 'habit_name': 'Nutrition', 'habit_type': 'good', 'description': 'We help you eat better'},
            {'language_code': 'en', 'habit_name': 'Breakfasting', 'habit_type': 'good', 'description': 'We help you start eating breakfast every day'}
        ]
        for habit in habits_data:
            Habit.objects.get_or_create(
                language_code_id=habit['language_code'],  # Foreign key relation
                habit_name=habit['habit_name'],
                habit_type=habit['habit_type'],
                defaults={'description': habit['description']}
            )

        self.stdout.write(self.style.SUCCESS('Successfully added habits'))

        # Adding steps
        steps_data = [
            "Record the time and number of cigarettes you smoke today",
            "Note the situation and emotions that led to each cigarette",
            "Reflect on why you want to quit—write down three reasons",
            "Decide on reducing your daily intake by 1-2 cigarettes",
            "Write down your quit date and share it with someone for support",
            "Plan small rewards for hitting milestones (e.g., a nice coffee, movie)",
            "Wait 30 minutes before smoking your first cigarette",
            "Distract yourself with a short walk or breathing exercises",
            "Track how delaying affects your craving",
            "Clear out lighters, ashtrays, and cigarettes from visible spaces",
            "Clean your smoking area to remove the smell of smoke",
            "Reward yourself for creating a smoke-free environment",
            "Swap one smoking break with a 5-minute walk or drink a glass of water",
            "Chew gum or snack on something healthy instead of smoking",
            "Write down how you felt after skipping a cigarette",
            "Select one cigarette time to skip today (e.g., after meals)",
            "Practice deep breathing to manage cravings",
            "Reflect on how your body feels with fewer cigarettes",
            "Calculate how many cigarettes you’ve cut down this week",
            "Write down any positive changes (e.g., better breathing, less coughing)",
            "Set a goal to reduce even further next week",
            "Pick two smoking times to skip today",
            "Use distractions like reading or a quick workout to avoid cravings",
            "Track how you felt throughout the day without those cigarettes",
            "Wait 10-15 minutes longer before each cigarette",
            "Focus on controlling cravings with breathing exercises",
            "Write down if delaying made it easier to smoke less",
            "Swap a smoking break for a healthy snack or activity (e.g., stretching)",
            "Spend 5 minutes doing deep breathing to relax",
            "Reflect on how you feel after choosing not to smoke",
            "Only smoke at specific times (e.g., after meals) and avoid casual smoking",
            "Avoid smoking in certain places (e.g., indoors, in the car)",
            "Reflect on how limiting when and where you smoke affects cravings",
            "Write down three ways your health has improved since cutting down",
            "Replace another cigarette with a 10-minute walk or relaxing activity",
            "Remind yourself of your reasons for quitting whenever you feel a craving",
            "Decide on a time of day to skip smoking entirely",
            "Practice mindfulness or meditation to cope with any stress",
            "Track how your cravings are evolving with fewer cigarettes",
            "Note how many cigarettes you’ve cut this week compared to last week",
            "Plan how you’ll continue cutting down further next week",
            "Reward yourself for sticking with your plan (e.g., treat, fun activity)",
            "Cut another 1-2 cigarettes from your daily routine",
            "Avoid smoking at a specific time of day (e.g., morning)",
            "Write down how this reduction is making you feel physically",
            "Use deep breathing or stretching exercises when you feel stressed",
            "Avoid using cigarettes as a way to cope with difficult situations",
            "Reflect on how alternative stress-relief techniques are working",
            "Wait at least 1 hour after feeling the urge to smoke before lighting up",
            "Distract yourself by doing something productive (e.g., work, hobby)",
            "Note how you felt after delaying and distracting yourself",
            "Choose one more cigarette to eliminate from your routine",
            "Replace the time you’d spend smoking with a healthy snack or drink",
            "Write down any positive physical changes you’re noticing",
            "Avoid smoking when around others who are smoking",
            "Choose a non-smoking activity with friends (e.g., coffee, sports)",
            "Reflect on how being around non-smokers helps you stick to your goal",
            "Replace two smoking breaks with a new activity or short walk",
            "Use deep breathing or mindfulness to reduce cravings",
            "Write down how skipping multiple cigarettes affected your cravings",
            "Plan how you’ll handle cravings on your quit day (e.g., gum, distractions)",
            "Remind yourself of your reasons for quitting and focus on your progress",
            "Set your final quit date and mentally prepare for the upcoming week",
            "Don’t smoke any cigarettes—today is your quit day",
            "Distract yourself with activities or hobbies when cravings hit",
            "Write down how it feels to go without smoking for an entire day",
            "Use nicotine alternatives (gum, lozenges) if needed to manage cravings",
            "Stay busy with fun, smoke-free activities (e.g., sports, socializing)",
            "Reflect on how well you managed cravings without smoking",
            "Replace smoking breaks with new, positive habits (e.g., stretching, reading)",
            "Engage in light physical activities to reduce stress and improve mood",
            "Write down any physical improvements (e.g., breathing, energy levels)",
            "Stay away from environments where you used to smoke",
            "Hang out with non-smokers or supportive friends",
            "Track how your cravings are decreasing as you avoid triggers",
            "When cravings hit, drink water or chew gum instead of smoking",
            "Practice mindfulness and deep breathing to reduce stress",
            "Reflect on how your overall mood and health are improving",
            "Avoid situations that might tempt you to smoke",
            "Remind yourself of your long-term health goals and benefits of quitting",
            "Reward yourself for each day of staying smoke-free",
            "Reflect on your journey and how long you’ve been smoke-free",
            "Treat yourself to something special as a reward for quitting",
            "Plan how to maintain your smoke-free lifestyle going forward",

            "Record the time you go to bed and wake up",
            "Note how you feel upon waking (alert, tired, etc.)",
            "Estimate how many times you woke up during the night",
            "Decide on your ideal sleep duration (e.g., 7-8 hours)",
            "Calculate your ideal bedtime based on your wake-up time",
            "Write down your sleep goal to commit to it",
            "Remove electronic devices (phone, TV) from your bedroom",
            "Make sure your room is dark by using blackout curtains or a sleep mask",
            "Adjust the room temperature to a comfortable level (cool, but not cold)",
            "Set an alarm for 15 minutes before your current bedtime to remind you to wind down",
            "Go to bed 15 minutes earlier than usual",
            "Avoid checking your phone or using screens right before bed",
            "Switch to decaf or herbal tea after lunch",
            "Avoid energy drinks or coffee in the late afternoon",
            "Drink water or other non-caffeinated beverages instead",
            "Spend 10-15 minutes doing something relaxing (e.g., reading, stretching)",
            "Dim the lights in your house an hour before bed",
            "Avoid stimulating activities (intense work, video games)",
            "Reflect on how much sleep you got each night",
            "Note any trends, such as better sleep on nights with no screens",
            "Adjust your goals for the next week based on this data",
            "Decide on a wake-up time and set an alarm",
            "Get up at the same time every day, even on weekends",
            "Avoid hitting snooze to reinforce the habit",
            "Set a reminder 30 minutes before your new bedtime to start winding down",
            "Go to bed at your scheduled time",
            "Track how easily you fall asleep at this time",
            "Remove clutter from your bedroom that could be distracting",
            "Place your phone on “Do Not Disturb” mode or in another room",
            "Use white noise or earplugs if necessary to block out sounds",
            "Try 5 minutes of deep breathing exercises before bed",
            "Practice progressive muscle relaxation (tense and release muscle groups)",
            "Listen to calming music or nature sounds to relax",
            "Avoid naps longer than 20-30 minutes",
            "Nap earlier in the day if needed, not too close to bedtime",
            "Set an alarm for naps to avoid oversleeping",
            "Incorporate a 20-30 minute walk, workout, or yoga during the day",
            "Avoid exercising too close to bedtime",
            "Stretch gently before bed to relax your body",
            "Reflect on how well you stuck to a consistent wake-up and bedtime",
            "Identify any areas that need improvement",
            "Adjust your schedule if needed for next week",
            "Spend 20-30 minutes outside in the morning sunlight",
            "Open your curtains first thing in the morning to let natural light in",
            "Eat breakfast or drink coffee near a window with sunlight",
            "Have your last meal at least 2-3 hours before bed",
            "Avoid eating spicy or heavy foods for dinner",
            "If you’re hungry before bed, have a light snack like a banana or almonds",
            "Try adding a new activity, like journaling, to your bedtime routine",
            "Reflect on your day and write down any thoughts or worries",
            "Experiment with reading a book or practicing gratitude before bed",
            "Set a 'no screen' rule 1 hour before bed",
            "Use blue light filters if you must use a device in the evening",
            "Find alternatives like listening to a podcast or reading a physical book",
            "Avoid alcohol 3-4 hours before bed, as it disrupts sleep",
            "If you drink alcohol, do so earlier in the day",
            "Substitute alcohol with a relaxing herbal tea in the evening",
            "Write down any thoughts or worries that might keep you awake",
            "Practice a short meditation session to calm your mind",
            "Stretch for 5-10 minutes to release tension",
            "Reflect on how well you slept and how rested you feel",
            "Review what helped you fall asleep more easily and stay asleep",
            "Adjust your bedtime routine for continued improvement",
            "Continue waking up and going to bed at the same time every day",
            "Set alarms or reminders to keep this routine consistent",
            "Use weekend days to reinforce this schedule",
            "Ensure your room remains dark, quiet, and cool",
            "Adjust your bedding if needed for extra comfort (e.g., pillows, blankets)",
            "Use essential oils (like lavender) or a diffuser to create a relaxing environment",
            "Avoid doing any work or engaging in stimulating conversations before bed",
            "Designate your bed solely for sleeping and relaxing",
            "Keep your phone away from your bed or use 'Do Not Disturb'",
            "Get morning sunlight as soon as you wake up",
            "Hydrate first thing in the morning to energize yourself",
            "Eat a healthy breakfast to regulate energy and promote better sleep cycles",
            "Stick to your bedtime and wake-up time, even on weekends",
            "Avoid staying up late or sleeping in significantly on weekends",
            "Plan fun weekend activities during the day to avoid evening distractions",
            "Stick to your calming routine of reading, stretching, or meditating",
            "Avoid any last-minute screen time or stress-inducing activities",
            "Continue to dim the lights 1 hour before bedtime",
            "Reflect on the improvements you’ve made in sleep quality and quantity",
            "Note how much more rested and energetic you feel",
            "Make a plan to maintain this routine long-term, even during busy periods",

            "Log every drink today and the emotions or situations that led to it.",
            "Write down what you hope to achieve by reducing your drinking.",
            "Reflect on times you felt triggered to drink and what caused them.",
            "Track any situations or feelings that led to drinking.",
            "Set a goal to reduce drinking this week (e.g., by 1-2 drinks).",
            "Identify and note an alternative activity to try when cravings hit.",
            "Log each drink, noting what preceded it.",
            "Reflect on why you started drinking today—habit, boredom, etc.",
            "List three personal reasons for wanting to cut down on alcohol.",
            "Review your reasons for drinking and how often they occur.",
            "Set a realistic weekly limit on drinks.",
            "Reflect on any challenges or patterns you’ve noticed.",
            "Write down three emotions you commonly feel before drinking.",
            "Try substituting one drink with a healthy alternative today.",
            "Journal how you felt after choosing the alternative.",
            "Set a goal to reduce by one additional drink today.",
            "Take a mindful pause before drinking to assess if you need it.",
            "Write about any discomfort or insights that came up.",
            "Count the total drinks for the week and reflect on any reduction.",
            "Note any new emotional insights or challenges.",
            "Celebrate one accomplishment from this week’s progress.",
            "Reduce your drink count today by 20% of last week’s average.",
            "Practice drinking mindfully, savoring each sip.",
            "Reflect on how mindful drinking affected your experience.",
            "Substitute one drink with a non-alcoholic beverage.",
            "Notice how your body and mind respond to the substitution.",
            "Reflect on any cravings and how you managed them.",
            "Reduce total drinks by one more today.",
            "Drink slowly, pausing between sips to check for satisfaction.",
            "Write about your experience with mindful drinking.",
            "Choose a healthy activity to do before drinking.",
            "Focus on how this new habit makes you feel.",
            "Reflect on whether the activity reduced your craving to drink.",
            "Continue mindful reduction.",
            "Write down any changes in your mood or physical sensations.",
            "Notice if there’s a time of day you typically want to drink.",
            "Replace another drink with a healthy habit.",
            "Note how your cravings evolved as you chose the substitute.",
            "Reflect on how this activity affected your mood.",
            "Review Week 2’s progress.",
            "Count the drinks reduced this week.",
            "Set a goal for continuing mindful reduction next week.",
            "Plan an alcohol-free day for today.",
            "Replace drinking time with a relaxing activity, like a walk.",
            "Journal how you felt after the alcohol-free day.",
            "Plan a social event without alcohol (e.g., coffee with a friend).",
            "Reflect on how it felt to socialize without drinking.",
            "Write down one benefit of a non-alcoholic social experience.",
            "Drink slowly and pause to check in with your satisfaction.",
            "Substitute one drink with an alternative (e.g., sparkling water).",
            "Write about your challenges in mindful drinking.",
            "Set another alcohol-free day.",
            "Aim for today to be alcohol-free and replace with an activity.", 
            "Write down how this day went and how it felt.",
            "Continue to reduce by one drink compared to last week.",
            "Reflect on whether you’re more aware of your drinking habits.",
            "Journal about any cravings and how you handled them.",
            "Schedule a non-drinking activity with friends.",
            "Notice how you feel socially without alcohol.",
            "Reflect on the positive aspects of non-alcoholic social events.",
            "Reflect on any changes in your habits or mood.",
            "Note the reduction in drinking from Week 1 to now.",
            "Set a target for next week, adding one more alcohol-free day.",
            "Increase alcohol-free days to three.",
            "Plan for an alcohol-free day and replace with a new habit.",
            "Notice if you feel differently about drinking on these days.",
            "Write down three emotions you’ve noticed before drinking.",
            "Try a new coping method for each emotion (e.g., journaling).",
            "Reflect on how these alternatives impact your urges.",
            "Practice mindfulness and self-reflection.",
            "Drink slowly, recognizing if you’re drinking out of habit.",
            "Use a different activity to distract if a craving arises.",
            "Increase alcohol-free days further.",
            "Aim for another alcohol-free day and try a rewarding activity.",
            "Reflect on physical and emotional improvements from drinking less.",
            "Write about challenges you faced and how you overcame them.",
            "Count how many alcohol-free days you've achieved.",
            "Celebrate the progress made this week.",
            "Reflect on your journey and improvements.",
            "Set future goals for alcohol reduction.",
            "Journal how you will continue the changes made going forward.",

            "Track every junk food item you eat today",
            "Drink a glass of water before every snack or meal to curb cravings",
            "Replace one junk food snack with a healthier alternative (e.g., fruit, nuts)",
            "Identify when and why you eat junk food (e.g., boredom, stress, social situations)",
            "Swap one sugary drink (e.g., soda) with water, herbal tea, or flavored water",
            "Choose one snack time to go without junk food and opt for a healthy option instead",
            "Reduce the portion size of one junk food item by 50% (e.g., smaller bag of chips)",
            "Eat mindfully today—pay attention to how you feel while eating",
            "Replace one junk food meal with a balanced, healthier meal (e.g., salad, grilled chicken)",
            "Replace any sugary snacks (e.g., candy, cookies) with fresh fruit or nuts",
            "Plan tomorrow’s meals ahead of time to avoid impulsive junk food eating",
            "Drink a glass of water every time you crave junk food",
            "Avoid sugary drinks entirely for the day (replace with water, herbal tea, or unsweetened drinks)",
            "Plan and prepare a healthy snack for the next few days",
            "Set a small reward for the end of the week if you reduce junk food consumption",
            "Replace a processed snack (e.g., chips, crackers) with a healthier option like nuts, fruits, or yogurt",
            "Add an extra serving of vegetables to a meal today",
            "Identify and clear out junk food from your home or workspace to reduce temptation",
            "Commit to one full day without any junk food",
            "Replace one meal with a home-cooked, balanced meal using whole foods",
            "Reflect on your progress this week and identify your biggest triggers for eating junk food",
            "Replace all snacks today with healthier options (e.g., fruit, nuts, seeds)",
            "Try eating smaller, more frequent meals to avoid cravings",
            "Drink at least 8 glasses of water throughout the day",
            "Plan all your meals for the day, making sure to avoid processed foods",
            "Have a fruit-based dessert instead of a sugary or processed one",
            "Add protein and fiber to each meal to keep you full longer (e.g., eggs, beans, whole grains)",
            "Avoid fast food for the entire day",
            "If cravings hit, snack on raw veggies or nuts instead of processed snacks",
            "Cook at least one meal from scratch today",
            "Focus on eating slowly and savoring your food to recognize when you’re full",
            "Avoid any chips or fried snacks today and swap them for fresh alternatives (e.g., air-popped popcorn)",
            "Cut down on portion sizes for any high-calorie or processed foods",
            "Write down healthy alternatives to your favorite junk foods",
            "Avoid packaged snacks today and eat only whole foods (fruits, vegetables, nuts)",
            "Drink water with every meal to help reduce cravings",
            "Eat a protein-rich breakfast (e.g., eggs, yogurt, or nuts) to start your day",
            "Avoid sugary desserts today and replace them with fruit or yogurt",
            "Snack on healthy fats (e.g., avocado, almonds) to keep you feeling full",
            "Avoid all processed foods today and focus only on whole foods",
            "Add two servings of vegetables to your meals today",
            "Plan tomorrow’s meals to ensure you have healthy options available",
            "Have another full junk food-free day",
            "Cook all your meals from scratch today, avoiding takeout or processed options",
            "Drink water or herbal tea instead of any sugary beverages",
            "Try a new healthy snack (e.g., hummus with veggies, rice cakes with nut butter)",
            "Eat three balanced meals and focus on portion control",
            "Replace one indulgent dessert with a healthier homemade option (e.g., fruit salad)",
            "Completely avoid all temptations at home by clearing out junk food items",
            "Choose healthier, homemade alternatives if cravings arise",
            "Eat a balanced, home-cooked dinner with protein, veggies, and healthy carbs",
            "If you crave junk food, allow yourself one small portion, but no more",
            "Focus on eating slowly and mindfully to enjoy your meals",
            "Drink a glass of water before every snack or meal",
            "Add a variety of fresh foods to your meals, especially vegetables and fruits",
            "Avoid all packaged snacks and eat fresh, whole foods instead",
            "Reflect on the progress you’ve made so far and write down how your body feels",
            "Plan your meals for the next week to ensure you stay junk food-free",
            "Keep healthier snack options easily accessible at home or work",
            "Avoid all processed foods for the day and focus on whole, nutrient-dense meals",
            "Reflect on your progress and how you feel after 21 days",
            "Set long-term goals for continuing to avoid junk food and incorporating healthy eating habits",
            "Reward yourself with a non-food-related treat for your hard work and success!",

            "Reflect on why you procrastinate (e.g., fear of failure, lack of motivation, or overwhelming tasks)",
            "Write down your thoughts in a journal or note",
            "Set a simple goal for today, such as completing a small task you've been avoiding",
            "Choose a task you tend to procrastinate on",
            "Break it down into smaller, manageable steps",
            "Set a timer for 25 minutes to work on the first step without distractions",
            "Create a daily schedule with designated work and rest periods",
            "Add your most important task to the top of your to-do list",
            "Commit to working on it for 15 minutes without interruption",
            "Identify the main distractions (phone, TV, social media) that prevent you from focusing",
            "Put your phone on 'Do Not Disturb' or use an app that blocks distractions",
            "Work for 30 minutes in a quiet space where distractions are minimized",
            "Choose one major task you’ve been avoiding",
            "Break it into tiny, achievable micro-goals (e.g., 'write 50 words' or 'organize 10 items')",
            "Complete the first micro-goal and celebrate the small win",
            "Pick a task to work on for 20 minutes",
            "After completing it, reward yourself with a small treat or break",
            "Write down how you feel after accomplishing this task and reward",
            "List your biggest time-wasting habits (e.g., scrolling through social media, watching TV)",
            "Set a daily time limit for these activities (e.g., 15-20 minutes)",
            "Replace wasted time with a productive activity, like reading or learning something new",
            "Pick a small task that can be done in two minutes or less (e.g., replying to an email, organizing a desk)",
            "Immediately complete it to build momentum",
            "Repeat this throughout the day to build a habit of quick action",
            "Write down your long-term goals and the steps to achieve them",
            "Create a vision board or visual reminder of these goals",
            "Spend a few minutes in the morning visualizing success and your ability to accomplish tasks",
            "Share a specific goal or task with a friend or colleague",
            "Set up a check-in time to report your progress",
            "Update your accountability partner once you've made progress or completed the task",
            "Create a time block for each task on your to-do list",
            "Dedicate 25 minutes to each block, followed by a 5-minute break",
            "Complete at least two time blocks today, avoiding multitasking",
            "Identify a task you’ve delayed due to perfectionism",
            "Commit to completing it with 'good enough' effort, instead of perfect results",
            "Focus on finishing the task, even if it’s not perfect",
            "Reflect on a past task where you procrastinated due to perfectionism",
            "Set a realistic standard for today’s task (e.g., 80% completion is acceptable)",
            "Complete the task with a focus on progress, not perfection",
            "Make a list of tasks you need to accomplish today",
            "Rank them in order of importance or deadline",
            "Tackle the most important task first, even if it’s challenging",
            "Acknowledge any procrastination you've experienced without judgment",
            "Write down a positive affirmation or self-compassionate thought (e.g., 'I am doing my best')",
            "Take a small action toward completing a task, focusing on progress rather than guilt",
            "Organize your workspace by decluttering",
            "Add items that promote productivity (e.g., a plant, inspiring quotes)",
            "Spend at least 30 minutes in this space focusing on your tasks",
            "Choose one task to work on today without distractions",
            "Set a timer for 25 minutes and focus solely on that task",
            "Take a 5-minute break before moving on to the next task",
            "Review the tasks you've completed over the past week",
            "Identify patterns in your productivity and areas for improvement",
            "Write down a few things you're proud of and areas you want to focus on",
            "Choose a task or habit you want to improve (e.g., work, exercise)",
            "Mark off each day you successfully complete the task on a calendar",
            "Aim to maintain an unbroken chain of progress for at least one week",
            "Commit to working on a task for just five minutes",
            "After five minutes, decide if you want to continue or stop",
            "Repeat this daily for any task you're avoiding",
            "Reflect on the progress you've made in overcoming procrastination",
            "Celebrate with a reward or treat for sticking to your plan",
            "Set new goals to continue building momentum in the coming weeks",

            "Select a book you’re excited about reading",
            "Set a simple daily goal (e.g., 5-10 pages or 10-15 minutes of reading)",
            "Place the book in a visible spot where you can easily access it",
            "Set aside a specific time of day (morning, lunch break, or before bed) for reading",
            "Add this reading time to your calendar or daily to-do list",
            "Start reading for at least 10 minutes at your designated time",
            "Find a quiet and comfortable place where you can focus on reading",
            "Turn off distractions like your phone or TV",
            "Gather any reading essentials (bookmark, highlighter, or notebook for notes)",
            "Stick to your designated reading time",
            "Read for at least 10 minutes today, focusing on enjoying the material",
            "Track your progress—how many pages you read or how long you spent reading",
            "Continue reading for 10 minutes at your scheduled time",
            "Reflect on how the reading is affecting your focus or relaxation",
            "Consider jotting down a key insight or interesting thought from your reading",
            "Try reading at a different time of day (morning vs. evening)",
            "See which time allows you to enjoy or focus more",
            "Adjust your reading time based on your findings",
            "Reflect on how consistent you were with reading this week",
            "Assess whether your 10-minute goal was achievable",
            "Set a goal to increase your reading time slightly for the next week",
            "Set a new goal of 15 minutes of reading per day",
            "Ensure you have a dedicated time slot to meet this new target",
            "Track your progress by writing down the time you spend reading",
            "Put your phone in another room or on airplane mode",
            "Avoid multitasking while reading (e.g., eating, checking notifications)",
            "Focus entirely on your book for the full 15 minutes",
            "Highlight or make notes on interesting sections of the book",
            "Write down a key takeaway or question you have from today’s reading",
            "Reflect on how the book is expanding your knowledge or imagination",
            "Try reading in a different spot, like a park, café, or another room in your home",
            "Notice how the change in environment affects your focus and enjoyment",
            "Choose your favorite location to continue reading in",
            "Gradually increase your reading time to 20 minutes",
            "Use a timer to ensure you stay focused for the full duration",
            "Track your progress and reflect on whether 20 minutes felt too long or just right",
            "If you're feeling adventurous, pick up a different genre (fiction, non-fiction, etc.)",
            "If possible, try a new reading format, such as an e-book or audiobook",
            "Note how the change affects your engagement with the material",
            "Reflect on how many days you met your reading goal",
            "Assess whether increasing your reading time was comfortable or challenging",
            "Plan to continue reading for at least 20 minutes per day next week",
            "Set a mini-goal for this week, like finishing a chapter or reaching a specific page number",
            "Write down your goal and track your daily progress toward it",
            "Reward yourself with a treat or break after completing the challenge",
            "Share an interesting insight or plot point from your book with a friend",
            "Join an online book discussion group or forum",
            "Write down a brief reflection on what you’re learning or enjoying so far",
            "Increase your daily reading time to 25 minutes today",
            "Break up your reading into two sessions if needed (e.g., 10 minutes in the morning, 15 at night)",
            "Reflect on whether this increase feels more engaging or too long",
            "Think about how what you’re reading connects to your personal interests or goals",
            "Write down any thoughts or ideas that resonate with you",
            "Reflect on how the book is influencing your thinking or mood",
            "Spend 5 minutes reading aloud or listening to an audiobook version of your book",
            "Notice how this different approach changes your experience",
            "Reflect on whether you prefer reading silently or out loud",
            "Find a friend, family member, or colleague who also likes to read",
            "Discuss what you’re reading with them or suggest reading the same book together",
            "Set a goal to check in with them regularly about your progress",
            "Reflect on whether reading has become a more enjoyable habit for you",
            "Assess if the daily 25-minute goal is sustainable",
            "Plan to maintain or adjust your goal for the next week based on your progress",
            "Set your reading goal to 30 minutes today",
            "Break the time into smaller sessions if needed (e.g., 15 minutes in the morning and evening)",
            "Track your time and notice how much progress you’ve made in your book",
            "Find a way to weave reading into your daily routines (e.g., read during breakfast, commute, or lunch)",
            "Set a reminder or alarm to keep reading a priority",
            "Treat reading like an important appointment or self-care practice",
            "Write down your reflections on how the habit has impacted your life",
            "Consider any personal growth, insights, or changes in mood from your reading",
            "Plan how to continue developing this habit in the future",
            "If you’re nearing the end of your current book, choose your next one",
            "Look for recommendations online or ask friends for suggestions",
            "Start reading a few sample chapters to see which book excites you",
            "Go back to a part of the book that you enjoyed or found insightful",
            "Re-read the section and reflect on why it stood out to you",
            "Write down how this part of the book has influenced your thinking",
            "Explore a new format, such as an article, short story, or poem",
            "If you’ve been reading non-fiction, try fiction, and vice versa",
            "Reflect on how the different format or style feels compared to your usual reading",
            "Reflect on your progress over the month",
            "Consider whether 30 minutes a day is sustainable long-term",
            "Plan to maintain your reading habit and adjust your goals as needed to keep it enjoyable",

            "Write down all sources of income (salary, side gigs, etc.)",
            "Categorize your expenses into fixed (e.g., rent, bills) and variable (e.g., groceries, entertainment)",
            "Review your overall income vs. expenses to understand your financial flow",
            "Look at your variable expenses for the past month",
            "Identify areas where you spend too much on non-essentials",
            "Make note of 3 spending areas you could cut back on",
            "Define your short-term goals (e.g., emergency fund, vacation)",
            "Define your long-term goals (e.g., retirement, house down payment)",
            "Break down your goals into specific amounts and timelines",
            "Create categories for your expenses: essentials, discretionary, and savings",
            "Review each expense and decide if it’s essential or discretionary",
            "Organize your expenses into a spreadsheet or app for easy tracking",
            "Allocate 50% of your income to essentials (e.g., rent, utilities)",
            "Allocate 30% to discretionary spending (e.g., entertainment, dining out)",
            "Allocate 20% to savings (e.g., emergency fund, retirement)",
            "Set up automatic transfers to your savings account (20% of income)",
            "Choose the day of the month for the transfer to occur",
            "Adjust your budget to accommodate this new savings habit",
            "Look back at your expenses and savings from the past week",
            "Identify areas where you went off-track or spent more than expected",
            "Make adjustments to your budget for the upcoming week",
            "List all subscriptions you are currently paying for (e.g., streaming services, apps)",
            "Cancel subscriptions you don’t use regularly or can live without",
            "Redirect any savings from canceled subscriptions into your emergency fund",
            "Plan your meals for the week and make a grocery list",
            "Cook at least 3 meals at home instead of dining out",
            "Track how much money you saved by eating at home",
            "Use a budgeting app (e.g., Mint, YNAB) to track every expense",
            "Record all your transactions throughout the day, no matter how small",
            "Review your spending at the end of the day to ensure it aligns with your budget",
            "Check how much you’ve saved so far",
            "Compare it to your initial savings goal and adjust if needed",
            "Celebrate your progress and set new mini-goals to stay motivated",
            "Review your budget categories and identify if you need to make adjustments",
            "Reallocate money from discretionary spending to savings if possible",
            "Update your budget to reflect any changes in your spending habits",
            "Commit to waiting 24 hours before making any non-essential purchase",
            "Write down the impulse purchase and review whether it was truly needed",
            "If you didn’t make the purchase, celebrate your self-control",
            "Look at your spending and saving from the past week",
            "Ensure you stayed within your budget for essentials and discretionary items",
            "Make any necessary adjustments for the following week",
            "Research potential side gigs or freelance work that fits your skills",
            "List 3 options that could increase your monthly income",
            "Dedicate time to exploring one of these income opportunities",
            "Commit to saving any extra money earned from side jobs or bonuses",
            "Set up an automatic transfer for this additional income to your savings account",
            "Track how much extra you’ve saved by the end of the month",
            "Plan upcoming purchases and look for coupons or sales",
            "Use apps or websites that offer discounts on items you need",
            "Track the money you saved by using these discounts",
            "Reassess your short-term and long-term savings goals based on your progress",
            "Adjust your goals to be more realistic if needed",
            "Create a timeline with new milestones to stay motivated",
            "If your income allows, increase your automatic savings transfers",
            "Allocate a set percentage or amount from any additional income",
            "Monitor how your savings grow as a result of these increases",
            "Create a sinking fund for a future large purchase (e.g., vacation, new gadgets)",
            "Set aside small amounts each month to gradually save for this",
            "Track your progress in saving for these larger expenses",
            "Check your expenses and savings for the week",
            "Ensure you’re on track to meet your goals for the month",
            "Make adjustments to your budget for the next week if needed",
            "Look into high-yield savings accounts with competitive interest rates",
            "Compare options and select one that fits your financial needs",
            "Open a high-yield savings account to maximize your savings growth",
            "Research retirement account options (e.g., 401k, IRA) and their benefits",
            "Choose the best retirement account based on your financial goals",
            "Learn about tax advantages and contribution limits",
            "Open an investment or retirement account if you don’t already have one",
            "Set up automatic contributions to this account",
            "Invest based on your risk tolerance and financial goals",
            "Set up automatic contributions to your retirement account (e.g., 401k, IRA)",
            "Decide on a monthly contribution amount based on your budget",
            "Monitor your contributions to ensure consistency",
            "Review your insurance policies (health, auto, home) to ensure they meet your needs",
            "Compare providers to find the best rates and coverage",
            "Consolidate or adjust policies to save on premiums",
            "Review your sinking fund progress for upcoming purchases",
            "Adjust your monthly contributions if necessary",
            "Make sure your sinking fund is on track to meet future needs",
            "Review how much you’ve saved, spent, and adjusted over the month",
            "Celebrate your successes and areas where you made progress",
            "Plan for the next month’s financial goals, building on what you’ve learned",

            "Decide how many days you’ll go to the gym this week (e.g., 3 times)",
            "Choose the exercises you’ll focus on (e.g., cardio, strength)",
            "Write down a fitness goal (e.g., build muscle, improve endurance)",
            "Go to the gym and do a light, 20-minute workout (e.g., cardio, light weights)",
            "Focus on learning proper form for each exercise",
            "Track how you felt during and after the session (e.g., energy, soreness)",
            "Take a rest day or do something light, like stretching or walking",
            "Hydrate and refuel your body with healthy foods",
            "Plan your next gym session for tomorrow",
            "Add 10 minutes to your session (e.g., cardio, strength training)",
            "Focus on a mix of cardio and strength exercises",
            "Write down how you felt after the workout",
            "Take a rest day or do yoga to improve flexibility",
            "Review how your muscles feel and adjust your intensity if needed",
            "Plan your next workout—consider increasing the difficulty",
            "Try a new machine or exercise (e.g., dumbbells, kettlebells)",
            "Increase the weights or reps slightly to challenge yourself",
            "Track your strength progress (e.g., weights lifted, reps completed)",
            "Write down how many days you made it to the gym and how you felt",
            "Set a new goal for next week (e.g., increase time, add exercises)",
            "Reward yourself for staying committed to your routine",
            "Plan a 40-minute workout with a mix of cardio and strength training",
            "Add 5-10 minutes of high-intensity cardio (e.g., treadmill, elliptical)",
            "Track how you feel after this longer session",
            "Spend 30 minutes focusing on strength exercises (e.g., free weights, machines)",
            "Aim for 3 sets of 8-12 reps for each exercise",
            "Write down your progress (e.g., weights lifted, number of sets completed)",
            "Take a rest day or do light activities like walking or swimming",
            "Focus on stretching to help muscle recovery",
            "Plan your next workout and set a small challenge (e.g., increase reps)",
            "Incorporate high-intensity interval training (HIIT) into your workout",
            "Alternate between 30 seconds of intense exercise and 1-minute rest periods",
            "Track your performance and how you felt after HIIT",
            "Do a gentle workout like yoga or light swimming to stay active",
            "Focus on hydrating and eating healthy foods to support recovery",
            "Review your fitness progress and plan for the next workout",
            "Add more weight or reps to your strength exercises",
            "Focus on compound movements like squats, deadlifts, and bench presses",
            "Reflect on how increasing intensity impacts your energy and progress",
            "Write down how much strength and endurance you’ve built this week",
            "Set goals for next week (e.g., try new exercises, increase workout time)",
            "Reward yourself for staying consistent with your routine",
            "Spend 30 minutes doing intense cardio (e.g., running, cycling, rowing)",
            "Increase your speed or resistance level to challenge yourself",
            "Track your endurance improvement and how you felt afterward",
            "Spend 40 minutes on lower body exercises (e.g., squats, lunges, leg presses)",
            "Aim for 3 sets of 10-12 reps for each exercise",
            "Track the weights you lifted and how many reps you completed",
            "Take a rest day or do light stretching and mobility exercises",
            "Hydrate well and focus on eating protein-rich foods to support muscle repair",
            "Reflect on how your body feels—adjust your intensity if necessary",
            "Add a new exercise or try a different workout style (e.g., circuit training)",
            "Increase the intensity slightly to challenge yourself",
            "Write down how this new exercise felt and if you’d continue it",
            "Spend 40 minutes on upper body exercises (e.g., bench press, pull-ups, shoulder press)",
            "Track your strength progress by increasing weights or reps",
            "Reflect on how your strength is improving over time",
            "Combine both lower and upper body exercises for a 45-minute session",
            "Focus on compound exercises to work multiple muscles at once (e.g., deadlifts)",
            "Write down your progress and note any areas for improvement",
            "Reflect on your fitness gains and improvements in stamina",
            "Set new goals for the next week (e.g., increase workout length or intensity)",
            "Reward yourself with something non-food-related (e.g., new gym gear)",
            "Plan a 50-minute workout with a balance of cardio and strength training",
            "Add a 5-minute cool-down with stretching to improve flexibility",
            "Write down how the longer session felt and if you could increase more",
            "Spend 45 minutes focusing on strength exercises with heavier weights",
            "Aim for 3 sets of 10-15 reps, increasing weights where possible",
            "Track your strength progress by writing down the weights you lifted",
            "Take a rest day or do light activities like walking or yoga",
            "Focus on hydrating and eating well to support muscle recovery",
            "Plan your next workout to build on this week’s strength progress",
            "Do 30-40 minutes of intense cardio (e.g., running, cycling) at a higher resistance",
            "Track how long you maintained a high-intensity level",
            "Reflect on your stamina progress and plan for the next cardio session",
            "Plan a 45-50 minute full-body workout that includes both strength and cardio",
            "Push yourself to lift slightly heavier or do more reps in each exercise",
            "Reflect on how you felt—track your strength and endurance improvements",
            "Spend 40-50 minutes targeting your upper or lower body (choose one)",
            "Increase weights or reps to challenge your muscles",
            "Write down how this focused session affected your muscle strength",
            "Reflect on the progress you’ve made in strength, endurance, and consistency",
            "Set new long-term fitness goals (e.g., increasing weights, running a 5k)",
            "Reward yourself with something special for completing 4 weeks of gym work",
            
            "Track everything you eat today.",
            "Add one serving of vegetables to a meal.",
            "Replace sugary drinks with water.",
            "Review your food tracking and identify areas where you're lacking (e.g., veggies, proteins).",
            "Choose a healthy snack for today (e.g., nuts, fruits).",
            "Add one more serving of vegetables to a different meal.",
            "Replace refined grains (e.g., white bread) with whole grains (e.g., whole wheat bread).",
            "Drink at least 8 glasses of water.",
            "Avoid sugary snacks and replace them with fruits.",
            "Make a healthy, protein-rich breakfast (e.g., eggs or yogurt).",
            "Add a healthy fat to your meal (e.g., avocado, olive oil).",
            "Continue tracking your food intake.",
            "Avoid processed snacks (chips, candy) today.",
            "Plan your meals for tomorrow to include whole foods.",
            "Drink water before every meal to prevent overeating.",
            "Eat mindfully by paying attention to your hunger levels.",
            "Include a healthy fat in one meal.",
            "Limit portion sizes, focusing on balance.",
            "Completely avoid sugary drinks today.",
            "Plan your meals for the next two days, focusing on variety.",
            "Snack on whole foods like fruits, vegetables, or nuts.",
            "Prepare meals for the next two days.",
            "Add protein to every meal.",
            "Drink water with every meal and snack.",
            "Try a new vegetable today (e.g., kale, broccoli).",
            "Swap unhealthy fats (e.g., butter) with healthy fats (e.g., olive oil).",
            "Eat a serving of fruit with a meal.",
            "Replace processed carbs (white bread, pasta) with whole grains.",
            "Focus on eating more lean proteins (e.g., chicken, beans).",
            "Avoid any packaged or processed snacks today.",
            "Limit any sugar intake to one small portion today.",
            "Add leafy greens to one meal.",
            "Drink water before every meal.",
            "Choose healthy snacks like fruits, nuts, or yogurt.",
            "Focus on a balanced meal with veggies, protein, and healthy fats.",
            "Eliminate sugary snacks and sodas for the day.",
            "Plan all three meals ahead of time.",
            "Add a variety of colors (vegetables) to each meal.",
            "Replace an unhealthy dessert with a fruit-based option.",
            "Add high-fiber foods (e.g., oats, beans) to your meals.",
            "Reduce processed sugars (use honey or natural sweeteners).",
            "Continue tracking what you eat for better accountability.",
            "Try cooking a new healthy recipe today.",
            "Snack on fruits or veggies instead of packaged snacks.",
            "Don't forget to drink at least 8 glasses of water.",
            "Avoid processed foods entirely today.",
            "Make a meal with fresh ingredients only (e.g., salad with protein).",
            "Add a healthy fat (e.g., nuts, avocado) to one meal.",
            "Ensure every meal includes a source of protein.",
            "Avoid sugary snacks for the entire day.",
            "Eat a balanced meal (protein, whole grains, and veggies).",
            "Avoid all packaged foods today.",
            "Cook a fresh meal with whole ingredients.",
            "Limit portion sizes to avoid overeating.",
            "Plan meals for the upcoming week, focusing on balance.",
            "Prepare a healthy snack for the next few days (e.g., pre-cut fruit).",
            "Try a new protein source (e.g., tofu, fish, lentils).",
            "Reflect on your progress and how you feel after 20 days.",
            "Identify what has worked well and what you can improve.",
            "Plan to maintain these habits in the coming weeks.",
            "Reward yourself with a non-food treat for sticking to the plan.",
            "Make a list of healthy go-to snacks and meals.",
            "Set small goals for the next month to maintain your healthy eating.",

            "Decide on a breakfast food you enjoy (e.g., oatmeal, smoothie, eggs).",
            "Buy the ingredients you’ll need for that breakfast.",
            "Set your alarm 15 minutes earlier to allow time for breakfast.",
            "Wake up 15 minutes earlier than usual.",
            "Prepare your chosen breakfast from Day 1.",
            "Eat your breakfast without distractions (no phone or TV).",
            "Choose a beverage to enjoy with breakfast (coffee, tea, juice).",
            "Set up your breakfast space (table or counter).",
            "Add something small, like a fruit or nut, to make breakfast more exciting.",
            "Try a new breakfast food or recipe.",
            "Plan your breakfast the night before to save time.",
            "Set a goal to have breakfast within the first 30 minutes of waking up.",
            "Decide on a specific time to eat breakfast each day (e.g., 7:30 AM).",
            "Add it to your morning routine.",
            "Eat breakfast at your chosen time, even if it's a small meal.",
            "Prepare breakfast with intention (no rush).",
            "Sit down at a table or dedicated space to eat.",
            "Focus on enjoying your meal and being mindful while eating.",
            "Choose a breakfast that includes protein or fiber for energy.",
            "Add a fruit or vegetable to your meal.",
            "Drink a glass of water alongside your breakfast.",
            "Prepare a smoothie or a homemade juice to complement your breakfast.",
            "Experiment with a new flavor combination or add a protein boost (e.g., protein powder, yogurt).",
            "Make sure to drink water as well to stay hydrated.",
            "Prepare ingredients or set out the items you'll need for tomorrow's breakfast.",
            "Make sure you have the necessary ingredients for tomorrow.",
            "Set your breakfast time and alarm 10 minutes earlier for preparation.",
            "Keep a log of the breakfast foods you've had so far.",
            "Note how you feel after eating breakfast (e.g., energized, full, satisfied).",
            "Reflect on your progress and how easy it is to get into the routine.",
            "Share breakfast with a friend or family member.",
            "Plan a breakfast gathering or share a recipe with others.",
            "Engage in conversation to make breakfast time more enjoyable.",
            "Review your goal of having breakfast every day.",
            "Adjust the timing or type of breakfast if needed.",
            "Celebrate your consistency with a small reward, like a treat or extra time to relax after breakfast.",
            "Prepare ingredients or full meals ahead of time (overnight oats, boiled eggs, smoothie packs).",
            "Store them in an easy-to-access spot.",
            "Choose a convenient breakfast from your meal prep in the morning.",
            "Try a new breakfast item you've never had before.",
            "Explore a different cultural breakfast food (e.g., avocado toast, poached eggs, or yogurt parfaits).",
            "Take note of what you like and want to repeat.",
            "Get creative with how you plate or serve your breakfast.",
            "Try adding different toppings or garnishes (e.g., nuts, seeds, or herbs).",
            "Take a photo of your breakfast to inspire creativity.",
            "Incorporate breakfast into a morning ritual (e.g., after meditation, morning stretch).",
            "Set a clear order of activities before and after breakfast.",
            "Start your day with a positive affirmation or habit that pairs well with your breakfast.",
            "Ensure your breakfast includes a balance of protein, fats, and carbohydrates.",
            "Experiment with portion sizes to find what makes you feel energized.",
            "Consider adding a healthy fat (avocado, nuts) or whole grains to your meal.",
            "Eat breakfast at the same time every day this week.",
            "Avoid skipping or replacing breakfast with snacks, even if you're in a rush.",
            "Set a reminder on your phone to remind you to eat.",
            "Make a special breakfast you've been craving or something new.",
            "Set aside more time to enjoy it fully.",
            "Include something indulgent (e.g., a pancake, a pastry) to celebrate your progress.",
            "Reflect on your breakfast habit over the past 19 days.",
            "Identify any challenges or areas for improvement.",
            "Make adjustments (e.g., adjusting the time or adding variety) if needed.",
            "Make breakfast a non-negotiable part of your day.",
            "Set a consistent time for breakfast even on weekends.",
            "Create a weekly grocery list to make sure you always have breakfast ingredients."

        ]
        for step in steps_data:
            Step.objects.get_or_create(
                language_code_id='en',  # Foreign key relation
                description=step
            )

        self.stdout.write(self.style.SUCCESS('Successfully added steps'))
