# Generated by Django 5.0.9 on 2024-10-01 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('habit_id', models.AutoField(primary_key=True, serialize=False)),
                ('habit_name', models.CharField(max_length=100)),
                ('habit_type', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=4)),
                ('description', models.TextField(blank=True)),
                ('gradient_color_start', models.CharField(default='#000000', help_text='Hex code for the gradient start color (default: black)', max_length=7)),
                ('gradient_color_end', models.CharField(default='#808080', help_text='Hex code for the gradient end color (default: gray)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language_code', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='habits.language')),
            ],
            options={
                'unique_together': {('habit_id', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language_code', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='habits.language')),
            ],
            options={
                'unique_together': {('step_id', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='HabStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.step')),
            ],
            options={
                'unique_together': {('habit', 'step', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_status', models.CharField(choices=[('not started', 'Not Started'), ('in progress', 'In Progress'), ('completed', 'Completed')], default='not started', max_length=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.user')),
            ],
            options={
                'unique_together': {('user', 'habit', 'step')},
            },
        ),
    ]
