# Generated by Django 5.0.9 on 2024-10-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_gradient_color_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='gradient_color_end',
            field=models.CharField(blank=True, help_text='Hex code for the gradient end color', max_length=7),
        ),
        migrations.AlterField(
            model_name='habit',
            name='gradient_color_start',
            field=models.CharField(blank=True, help_text='Hex code for the gradient start color', max_length=7),
        ),
    ]
