# Generated by Django 5.0.9 on 2024-11-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_gradient_color_end_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'habit')},
        ),
        migrations.AddField(
            model_name='userprogress',
            name='completed_tasks_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_day',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='progress_status',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='step',
        ),
    ]
