# Generated by Django 5.0.9 on 2024-11-07 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_userprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_completed', models.BooleanField(default=False)),
                ('task_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.userprogress')),
            ],
        ),
    ]
